# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Cultural Heritage Data Guides - Python
author: The Royal Danish Library - Staff
logo: DKB_logo_simplified_black_RGB.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 300  # Timeout in seconds (5 minutes) for cells that process large datasets

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex


# Information about where the book exists on the web
repository:
  url: https://github.com/kb-dk/cultural-heritage-data-guides-Python
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  announcement: |
    <div>
    <a href="https://www.kb.dk/services/kulturarv-til-forskning-og-studier/kulturarvssamlingerne-som-data">
    <img src="https://kb-dk.github.io/cultural-heritage-data-guides-R/img/DKB_logo_simplified_black_RGB.png" alt="The Royal Danish Library logo" title="Back to Royal Danish Library's webpage" 
    style="width: 15%; height: auto;" Go to Cultural Heritage Collection as Data></a>
    <a href="https://www.kb.dk/services/kulturarv-til-forskning-og-studier/kulturarvssamlingerne-som-data" style="color: orange;">Back to Royal Danish Library's webpage</a>
    </div>
